
#-----------------------------------------------------------------------------------------------------------------------------------------------
# 3D GPU CCL 26
#-----------------------------------------------------------------------------------------------------------------------------------------------

GPU 3D 8-way connectivity:
  execute: false
  
  # ------------------------------------------------------------------------------
  # Tests to perform and their number of repetitions
  # ------------------------------------------------------------------------------
  
  perform: 
    correctness:        false
    average:            true
    average_with_steps: false
    density:            false
    granularity:        false
    memory:             false
  
  correctness_tests: 
    eight_connectivity_standard: true
    eight_connectivity_steps:    true
    eight_connectivity_memory:   false
  
  # Number of tests repetitions 
  tests_number: 
    average:             1 
    average_with_steps:  5
    density:            10
    granularity:        10 
  
  # ------------------------------------------------------------------------------
  # List of 3D CPU CCL algorithms to test
  # ------------------------------------------------------------------------------
  
  algorithms: 
  #  - 3D_labeling_NULL
  #  - CUDA_UF_3D
  #  - CUDA_BUF_3D
    - CUDA_BE_3D
  
  # Algorithms which require to specify a labels solver are: SAUF, BBDT, CCIT, LSL, CTB, PRED, and DRAG
  # Possible labels solvers are: UF, UFPC, RemSP, TTA
  # LSL requires also a version specifier: STD, STDZ, RLE, RLEZ; only UF and TTA solvers can be used with LSL
  # Algorithms which don't require to specify a labels solver are: DiStefano, CT, SBLA, NULL
  
  # ------------------------------------------------------------------------------
  # Datasets to use for each test
  # ------------------------------------------------------------------------------
  
  # Note that perform correctness tests on labeling_NULL algorithm does not make sense
  #check_datasets: ["check", "3dpes", "fingerprints", "hamlet", "medical", "mirflickr", "tobacco800", "xdocs"]
  check_datasets: ["skulls", "3dcheck"]
  
  # List of datasets on which "Average Runtime Tests" shall be run
  #average_datasets: ["3dpes", "fingerprints", "hamlet", "medical", "mirflickr", "tobacco800", "xdocs"]
  average_datasets: ["3dcheck"]
  
  # List of datasets on which "Average Runtime Tests With Steps" shall be run
  #average_datasets_with_steps: ["3dpes", "fingerprints", "hamlet", "medical", "mirflickr", "tobacco800", "xdocs"]
  average_datasets_with_steps: ["skulls", "random3D"]
  
  # List of datasets on which "Memory Tests" shall be run
  #memory_datasets: ["3dpes", "fingerprints", "hamlet", "medical", "mirflickr", "tobacco800", "xdocs"]
  memory_datasets: ["skulls"]

  # Save the results of each run test
  save_middle_tests: {average: false, average_with_steps: false, density: false, granularity: false}
