%YAML:1.2
---
##########################################
# THIS IS THE YACCLAB CONFIGURATION FILE #
##########################################

# -------------------- #
#   Benchmark Tests    #
# -------------------- #

${YACCLAB_CONFIG_2D}${YACCLAB_CONFIG_CUDA_2D}${YACCLAB_CONFIG_3D}${YACCLAB_CONFIG_CUDA_3D}

# -------------------- #
# Additional utilities #
# -------------------- #

# Directory for input/output paths
paths: {input: "${YACCLAB_INPUT_DATASET_PATH}", output: "${YACCLAB_OUTPUT_RESULTS_PATH}"}

# Save the returned number of components in output files
write_n_labels: false

# Save labeled image (TODO: remove this option from tests and add a specific tools for doing that in YACCLAB) 
color_labels: {average: false, density: false} #TODO

os: "${YACCLAB_OS}"

##########################################
# This is the YACCLAB configuration file #
##########################################
