
#-----------------------------------------------------------------------------------------------------------------------------------------------
# 2D GPU CCL 8
#-----------------------------------------------------------------------------------------------------------------------------------------------

GPU 2D 8-way connectivity:
  execute: false
  
  # ------------------------------------------------------------------------------
  # Tests to perform and their number of repetitions
  # ------------------------------------------------------------------------------
  
  # Kind of tests to execute
  perform: 
    correctness:        true
    average:            false
    average_with_steps: false
    density:            false
    granularity:        false
    memory:             false
  
  correctness_tests: 
    eight_connectivity_standard: true
    eight_connectivity_steps:    false
    eight_connectivity_memory:   false
  
  # Number of tests repetitions 
  tests_number: 
    average:             5 
    average_with_steps:  1
    density:             1
    granularity:         1 
  
  # ------------------------------------------------------------------------------
  # List of 2D GPU CCL algorithms to test
  # ------------------------------------------------------------------------------
  
  algorithms:
  #  - CUDA_LE
  #  - CUDA_BE
  #  - CUDA_KE
  #  - CUDA_DLP
  #  - CUDA_UF
    - CUDA_UF_naive
  #  - CUDA_TUF
  #  - CUDA_BUF
  #  - CUDA_TBUF 
  
  # ------------------------------------------------------------------------------
  # Datasets to use for each test
  # ------------------------------------------------------------------------------
  
  # Note that perform correctness tests on labeling_NULL algorithm does not make sense
  #check_datasets: ["check", "3dpes", "fingerprints", "hamlet", "medical", "mirflickr", "tobacco800", "xdocs"]
  check_datasets: ["check"]
  
  # List of datasets on which "Average Runtime Tests" shall be run
  #average_datasets: ["3dpes", "fingerprints", "hamlet", "medical", "mirflickr", "tobacco800", "xdocs"]
  average_datasets: ["check"]
  
  # List of datasets on which "Average Runtime Tests With Steps" shall be run
  #average_datasets_with_steps: ["3dpes", "fingerprints", "hamlet", "medical", "mirflickr", "tobacco800", "xdocs"]
  average_datasets_with_steps: ["fingerprints"]
  
  # List of datasets on which "Memory Tests" shall be run
  memory_datasets: ["3dpes", "fingerprints", "hamlet", "medical", "mirflickr", "tobacco800", "xdocs"]
  
  # Save the results of each run test
  save_middle_tests: {average: false, average_with_steps: false, density: false, granularity: false}
